<a href="https://colab.research.google.com/github/chaeeuen/python-machine-learing/blob/main/3_8_%E1%84%89%E1%85%A6%E1%84%89%E1%85%A7%E1%86%AB_%E1%84%86%E1%85%AE%E1%86%AB%E1%84%8C%E1%85%A6_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

1.25.2


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector= np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
memory_size = null_vector.nbytes
print(memory_size, "bytes")

80 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix = np.arange(9)
matrix1 = matrix.reshape(3,3)

print(matrix1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
array1 = np.array([1,2,0,0,4,0])
nonzero_indicies = np.nonzero(array1)[0]

print(nonzero_indicies)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
identity_matrix1 = np.identity(3)
print(identity_matrix1)

identity_matrix2 = np.eye(3)
print(identity_matrix2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.96790866 0.45747937 0.72743898]
  [0.60703859 0.10798411 0.04002559]
  [0.47624811 0.13542487 0.81497266]]

 [[0.18373514 0.02851001 0.46800931]
  [0.82981808 0.66889023 0.47995097]
  [0.81208233 0.400936   0.92293925]]

 [[0.91063131 0.26889445 0.06948275]
  [0.89912859 0.51531884 0.04236577]
  [0.20505681 0.41903061 0.69538297]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
random_array1 = np.random.random((10,10))
min = np.min(random_array1)
max = np.max(random_array1)

print(random_array1)
print(min)
print(max)

[[0.78577408 0.78995541 0.15793086 0.14348837 0.08909537 0.86889631
  0.54360026 0.83367799 0.17575958 0.21799862]
 [0.65550394 0.12645199 0.88623626 0.24344366 0.1163746  0.64445931
  0.41308633 0.82606386 0.85928635 0.40533509]
 [0.62433199 0.34814185 0.55333739 0.26535553 0.03741739 0.06113266
  0.38666561 0.53882472 0.19863653 0.36885622]
 [0.12493135 0.54432148 0.82998027 0.42433616 0.11415541 0.20073831
  0.09433064 0.21242731 0.25948505 0.79153786]
 [0.05743118 0.45837486 0.48626516 0.22093919 0.5774059  0.45660202
  0.57531739 0.34233573 0.95154109 0.59660781]
 [0.19743402 0.9423624  0.75207854 0.45254023 0.65132322 0.57700584
  0.25468276 0.32856832 0.52396053 0.08938116]
 [0.71314283 0.02716468 0.8537591  0.98426627 0.97385112 0.3141905
  0.91389888 0.43645568 0.25867852 0.40089584]
 [0.39831825 0.46533229 0.80006828 0.0655136  0.60775922 0.59691513
  0.34345377 0.47076795 0.4173535  0.14904752]
 [0.75540331 0.10979353 0.38363142 0.29801279 0.61327052 0.8893124
  0.01792013 0

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
random_array2 = np.random.random(30)
mean = np.mean(random_array2)

print(random_array2)
print(mean)

[0.67008743 0.8122292  0.76512607 0.8326826  0.09010998 0.84454164
 0.219264   0.58117877 0.40723271 0.172809   0.18807308 0.14652409
 0.84916431 0.91654976 0.05935097 0.29956339 0.93912195 0.18904126
 0.51783079 0.42962372 0.81841487 0.27751623 0.43895009 0.82920356
 0.32153378 0.23729633 0.77636315 0.88337619 0.82103445 0.47484813]
0.5269547161721988


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array3 = np.zeros((5,5))

array3[0,:] = 1
array3[:,0] = 1
array3[4,:] = 1
array3[:,4] = 1

print(array3)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
matrix = np.zeros((5,5), dtype='int32')

matrix[1,0] = 1
matrix[2,1] = 2
matrix[3,2] = 3
matrix[4,3] = 4

print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix = np.zeros((8,8), dtype='int32')

matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
index_100th = np.unravel_index(100, (6, 7, 8))
print(index_100th)

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
random_matrix = np.random.random((5,5))
mean = np.mean(random_matrix)
std = np.std(random_matrix)

normalized_matrix = (random_matrix-mean)/std
print(normalized_matrix)

[[-1.43525276e+00  1.06946676e+00  2.97641673e-01 -5.34085497e-01
   1.81463322e+00]
 [-1.52466381e+00  6.39021210e-01 -8.48565213e-04  1.18722668e+00
   1.27159426e+00]
 [-1.89924911e-01 -4.73993725e-01 -6.93118893e-01  1.12735855e+00
  -5.86044363e-01]
 [-1.28392782e+00 -5.99555872e-01  4.92095275e-01  5.62061673e-02
  -1.64752583e+00]
 [ 8.32628856e-01  1.30578904e+00 -1.34403213e+00  7.49260446e-01
  -5.29947969e-01]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color_dtype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
result = np.dot(A,B)

print(result)

[[0.9136543  1.08059531]
 [0.97796386 1.24323641]
 [1.03511455 1.21102602]
 [1.09954273 1.28994435]
 [0.51647755 0.5919092 ]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
only Z<Z>Z is not legal.

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan, 0, 0.0

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)

common_values = np.intersect1d(Z1, Z2)
print(common_values)

[9 1 8 5 7 8 3 1 0 0]
[2 9 9 3 8 5 9 7 1 1]
[1 3 5 7 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
True

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
dates = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
result = np.empty_like(A)

np.add(A,B,out=result)
np.negative(A, out=A)
np.divide(A,2,out=A)
np.multiply(A, result, out=result)

print(result)

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
random_array = np.random.rand(5) * 100
integer_part_modulus = random_array % 1

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
matrix = np.arange(5).reshape(1, -1) + np.zeros((5, 5), dtype=int)
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)
print(sorted_vector)

[0.07687487 0.15689359 0.28640138 0.30953126 0.47320842 0.62442833
 0.670773   0.67640058 0.73513648 0.73578321]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

equal_arrays = np.array_equal(A, B)
print(equal_arrays)

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
Z = np.random.rand(10)
max_index = np.argmax(Z)
Z[max_index] = 0

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
distances = np.abs(Z - v)
closest_index = np.argmin(distances)
closest_value = Z[closest_index]

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3