<a href="https://colab.research.google.com/github/chaeeuen/python-machine-learing/blob/main/3_8_%E1%84%89%E1%85%A6%E1%84%89%E1%85%A7%E1%86%AB_%E1%84%86%E1%85%AE%E1%86%AB%E1%84%8C%E1%85%A6_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vector= np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:

Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
Z=np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
matrix = np.arange(9)
matrix1 = matrix.reshape(3,3)

print(matrix1)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
array1 = np.array([1,2,0,0,4,0])
nonzero_indicies = np.nonzero(array1)[0]

print(nonzero_indicies)

[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [10]:
identity_matrix1 = np.identity(3)
print(identity_matrix1)

identity_matrix2 = np.eye(3)
print(identity_matrix2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [11]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.34469885 0.23442213 0.52757689]
  [0.60457998 0.71945529 0.12967365]
  [0.73730205 0.59344303 0.4101304 ]]

 [[0.31058793 0.69244533 0.42174796]
  [0.9972927  0.50600452 0.17757364]
  [0.77775853 0.05606099 0.7412204 ]]

 [[0.41557455 0.40515988 0.8541315 ]
  [0.67410299 0.89253375 0.49463966]
  [0.90011404 0.29780262 0.74155847]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [12]:
random_array1 = np.random.random((10,10))
min = np.min(random_array1)
max = np.max(random_array1)

print(random_array1)
print(min)
print(max)

[[0.58018967 0.50162021 0.6752186  0.66689916 0.43128234 0.11030848
  0.6111987  0.92316262 0.5469649  0.0707549 ]
 [0.71452317 0.55937995 0.7594148  0.28860753 0.80875033 0.08971788
  0.81191369 0.79337965 0.58995842 0.81680834]
 [0.75872433 0.59405379 0.82308214 0.43753355 0.86600863 0.16892991
  0.50463374 0.88500697 0.81760824 0.13288572]
 [0.87547168 0.01767162 0.80885041 0.19425145 0.54440493 0.44951668
  0.50136106 0.96260007 0.49647127 0.15768996]
 [0.31841321 0.2616479  0.35024669 0.74496773 0.8802392  0.97376245
  0.48623888 0.99133183 0.83104728 0.25824754]
 [0.79384605 0.69304678 0.09944634 0.40028423 0.99306634 0.37391747
  0.67987521 0.28096834 0.59206537 0.79751621]
 [0.33682733 0.83597408 0.24968794 0.17030985 0.80529795 0.13725129
  0.3999419  0.21541786 0.71609353 0.33477561]
 [0.378833   0.20245061 0.24816314 0.46841526 0.62996658 0.65493744
  0.18605421 0.74567058 0.54869508 0.72863864]
 [0.88767752 0.42165612 0.92260457 0.20450051 0.73324688 0.43349684
  0.66520669

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [13]:
random_array2 = np.random.random(30)
mean = np.mean(random_array2)

print(random_array2)
print(mean)

[0.10406633 0.72870267 0.11962063 0.13303762 0.38245513 0.41309923
 0.84943319 0.28961568 0.64291737 0.27075377 0.83973563 0.38624537
 0.97060161 0.95134158 0.95370138 0.36939871 0.51367052 0.17784512
 0.48560699 0.74798551 0.67230332 0.60415612 0.01384341 0.21577072
 0.33206569 0.57904666 0.24859919 0.71047982 0.84915777 0.52860104]
0.502795258616416


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
array3 = np.zeros((5,5))

array3[0,:] = 1
array3[:,0] = 1
array3[4,:] = 1
array3[:,4] = 1

print(array3)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [15]:
nan
False
False
nan
True
False

NameError: name 'nan' is not defined

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
matrix = np.zeros((5,5), dtype='int32')

matrix[1,0] = 1
matrix[2,1] = 2
matrix[3,2] = 3
matrix[4,3] = 4

print(matrix)

Z= np.diag(1+np.arange(4), k=-1)
print(Z)

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
matrix = np.zeros((8,8), dtype='int32')

matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1

print(matrix)

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
index_100th = np.unravel_index(99, (6, 7, 8))
print(index_100th)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
random_matrix = np.random.random((5,5))
mean = np.mean(random_matrix)
std = np.std(random_matrix)

normalized_matrix = (random_matrix-mean)/std
print(normalized_matrix)

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color_dtype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
result = np.dot(A,B)

print(result)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
Z = np.arange(11)
Z[(3<Z )& (Z<8)] *= -1
print(Z)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
only Z<Z>Z is not legal.

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [16]:
nan, 0, 0.0

NameError: name 'nan' is not defined

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,10,10)
print(Z2)

common_values = np.intersect1d(Z1, Z2)
print(common_values)

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
True

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [17]:
dates = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [22]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)



array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [23]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)

[8. 2. 3. 2. 9. 8. 7. 3. 6. 3.]
[8. 2. 3. 2. 9. 8. 7. 3. 6. 3.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [24]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [25]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.05957331 0.11610696 0.23917836 0.27721935 0.47740862 0.50845933
 0.72167117 0.7331289  0.74964715 0.92227625]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [26]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
print(equal)

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [27]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.96121049 0.24480723 0.91982447 0.30424829 0.46953577 0.25456732
 0.55646616 0.75252856 0.48708573 0.56450779]
[0.12776593 0.19960348 1.45027116 0.27772489 0.54035196 0.95955174
 0.2743459  0.42822979 1.53763013 0.59063052]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [28]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.49453473 0.07184    0.26302239 0.         0.49898734 0.21038931
 0.36953335 0.30259825 0.44940807 0.41186817]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [30]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

42


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [31]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [32]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [33]:
# column 1
Z = np.random.randint(0,10,(3,3))

print(Z)
print(Z[Z[:,0].argsort()])

[[9 8 6]
 [5 3 4]
 [2 2 7]]
[[2 2 7]
 [5 3 4]
 [9 8 6]]


In [35]:
# column 2
print(Z)
print(Z[Z[:,1].argsort()])

[[9 8 6]
 [5 3 4]
 [2 2 7]]
[[2 2 7]
 [5 3 4]
 [9 8 6]]


In [36]:
# column 3
print(Z)
print(Z[Z[:,2].argsort()])

[[9 8 6]
 [5 3 4]
 [2 2 7]]
[[5 3 4]
 [9 8 6]
 [2 2 7]]
